<?php
/**
 * Redis门面IDE类型提示文件
 * 这个文件提供Redis门面的完整方法提示
 */

namespace Illuminate\Support\Facades {
    /**
     * Redis门面类
     * 
     * @method static mixed get(string $key)
     * @method static bool set(string $key, mixed $value, int $ttl = null)
     * @method static bool setex(string $key, int $ttl, mixed $value)
     * @method static bool setnx(string $key, mixed $value)
     * @method static bool del(string|array $key)
     * @method static bool exists(string $key)
     * @method static int expire(string $key, int $ttl)
     * @method static int ttl(string $key)
     * @method static bool rename(string $oldKey, string $newKey)
     * @method static int incr(string $key)
     * @method static int incrby(string $key, int $increment)
     * @method static float incrbyfloat(string $key, float $increment)
     * @method static int decr(string $key)
     * @method static int decrby(string $key, int $decrement)
     * @method static array mget(array $keys)
     * @method static bool mset(array $keyValues)
     * @method static array keys(string $pattern)
     * @method static int dbsize()
     * @method static bool flushdb()
     * @method static bool flushall()
     * @method static string randomkey()
     * @method static bool select(int $db)
     * @method static bool move(string $key, int $db)
     * @method static bool persist(string $key)
     * @method static string type(string $key)
     * @method static int strlen(string $key)
     * @method static string getrange(string $key, int $start, int $end)
     * @method static int setrange(string $key, int $offset, string $value)
     * @method static string getset(string $key, mixed $value)
     * @method static int append(string $key, string $value)
     * @method static int lpush(string $key, mixed $value)
     * @method static int rpush(string $key, mixed $value)
     * @method static mixed lpop(string $key)
     * @method static mixed rpop(string $key)
     * @method static int llen(string $key)
     * @method static array lrange(string $key, int $start, int $stop)
     * @method static mixed lindex(string $key, int $index)
     * @method static bool lset(string $key, int $index, mixed $value)
     * @method static int lrem(string $key, int $count, mixed $value)
     * @method static mixed ltrim(string $key, int $start, int $stop)
     * @method static int sadd(string $key, mixed $member)
     * @method static int srem(string $key, mixed $member)
     * @method static bool sismember(string $key, mixed $member)
     * @method static array smembers(string $key)
     * @method static int scard(string $key)
     * @method static mixed spop(string $key)
     * @method static mixed srandmember(string $key, int $count = 1)
     * @method static int hset(string $key, string $field, mixed $value)
     * @method static mixed hget(string $key, string $field)
     * @method static bool hdel(string $key, string $field)
     * @method static bool hexists(string $key, string $field)
     * @method static array hgetall(string $key)
     * @method static array hkeys(string $key)
     * @method static array hvals(string $key)
     * @method static int hlen(string $key)
     * @method static int hincrby(string $key, string $field, int $increment)
     * @method static float hincrbyfloat(string $key, string $field, float $increment)
     * @method static int zadd(string $key, float $score, mixed $member)
     * @method static int zrem(string $key, mixed $member)
     * @method static float zscore(string $key, mixed $member)
     * @method static int zcard(string $key)
     * @method static array zrange(string $key, int $start, int $stop, bool $withscores = false)
     * @method static array zrevrange(string $key, int $start, int $stop, bool $withscores = false)
     * @method static array zrangebyscore(string $key, float $min, float $max, array $options = [])
     * @method static array zrevrangebyscore(string $key, float $max, float $min, array $options = [])
     * @method static int zcount(string $key, float $min, float $max)
     * @method static int zrank(string $key, mixed $member)
     * @method static int zrevrank(string $key, mixed $member)
     * @method static int zremrangebyrank(string $key, int $start, int $stop)
     * @method static int zremrangebyscore(string $key, float $min, float $max)
     * @method static bool ping()
     * @method static string echo(string $message)
     * @method static bool auth(string $password)
     * @method static bool quit()
     * @method static array info(string $section = null)
     * @method static array time()
     * @method static bool save()
     * @method static bool bgsave()
     * @method static int lastsave()
     * @method static bool bgrewriteaof()
     * @method static string role()
     * @method static array slowlog(string $command, int $length = null)
     * @method static bool config(string $command, string $key = null, string $value = null)
     * @method static array client(string $command, string $value = null)
     * @method static bool subscribe(array $channels, \Closure $callback)
     * @method static bool psubscribe(array $patterns, \Closure $callback)
     * @method static bool publish(string $channel, string $message)
     * @method static bool unsubscribe(array $channels = null)
     * @method static bool punsubscribe(array $patterns = null)
     * @method static bool watch(array $keys)
     * @method static bool unwatch()
     * @method static array multi()
     * @method static array exec()
     * @method static bool discard()
     * @method static \Illuminate\Redis\Connections\Connection connection(string $name = null)
     * @method static \Illuminate\Contracts\Redis\Factory getRedis()
     * @method static void macro(string $name, callable $macro)
     * @method static void mixin(object $mixin, bool $replace = true)
     * @method static bool hasMacro(string $name)
     * @method static void flushMacros()
     * @method static mixed macroCall(string $method, array $parameters)
     */
    class Redis {
        // 这个类只是为IDE提供类型提示，实际实现由Laravel的门面系统处理
    }
} 